name: go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  Lint:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...
        
      - name: Run unit test.
        run: make test-coverage
